name: Build and test result

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version:
        - "3.8"
        os:
        - ubuntu-latest
        - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run buildme.sh
      run: |
        WITH_PYTHON=`which python` ./buildme.sh ~/dist
    - name: Upload Plone Installer from build
      uses: actions/upload-artifact@v2
      with:
        name: Plone-Installer-${{ matrix.os }}
        path: "~/dist/Plone-5.2.2-UnifiedInstaller.tgz"
  check-install:
    needs: build
    strategy:
      matrix:
        buildartifact:
        - Plone-Installer-ubuntu-latest
        - Plone-Installer-macos-latest
        python-version:
        - "2.7"
        - "3.6"
        - "3.7"
        - "3.8"
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download Plone-Installer
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.buildartifact }}
      - name: Test Installer
        shell: bash
        run: |
          tar xzf Plone-5.2.2-UnifiedInstaller.tgz
          cd Plone-5.2.2-UnifiedInstaller/tests
          WITH_PYTHON=`which python` python testall.py

