name: Build and test result

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run buildme.sh
      run: |
        WITH_PYTHON=`which python` ./buildme.sh ~/dist
    - name: Upload Plone Installer from build
      uses: actions/upload-artifact@v2
      with:
        name: Plone-Unified-Installer
        path: ~/dist/*.tgz
  test:
    needs: build
    strategy:
      matrix:
        python-version:
        - "2.7"
        - "3.6"
        - "3.7"
        - "3.8"
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install GNU tar
      # Work around https://github.com/actions/virtual-environments/issues/1534#issuecomment-699617344
      # by using GNU tar instead of BSD tar.
      if: matrix.os == 'macos-latest'
      run: |
        brew install gnu-tar
        echo PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" >> $GITHUB_ENV
    - name: Increase WAIT for Service on macos
      if: matrix.os == 'macos-latest'
      run: |
        echo PLONE_SERVER_START_WAIT="120" >> $GITHUB_ENV
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download Plone-Installer
      uses: actions/download-artifact@v2
      with:
        name: Plone-Unified-Installer
    - name: Display structure of downloaded files
      run: ls -R
    - name: Test Installer
      shell: bash
      run: |
        tar xzf Plone-*-UnifiedInstaller.tgz
        mv Plone-*-UnifiedInstaller ../installer
        cd ..
        mkdir tmp
        ls -la
        cd installer/tests
        WITH_TEMP="../../tmp" WITH_PYTHON="`which python`" python testall.py

